name: firesearch_sdk
description: An sdk for Firesearch
version: 0.1.3
repository: https://github.com/uris77/firesearch_sdk
homepage: https://github.com/uris77/firesearch_sdk

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  http: ^0.13.3
  meta: ^1.3.0
  json_annotation: ^4.0.1
  freezed_annotation: ^0.14.2

dev_dependencies:
  test: ^1.17.4
  very_good_analysis: ^2.0.3
  freezed: ^0.14.2
  build_runner: ^2.0.3
  json_serializable: ^4.1.2
  mocktail: ^0.1.2
