name: firesearch_sdk
description: An sdk for Firesearch
version: 0.1.0
repository: https://github.com/uris77/firesearch_sdk
homepage: https://github.com/uris77/firesearch_sdk

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  http: ^0.13.1
  meta: ^1.3.0
  json_annotation: ^4.0.1
  freezed_annotation: ^0.14.1

dev_dependencies:
  test: ^1.16.8
  very_good_analysis: ^2.0.0
  freezed: ^0.14.1+2
  build_runner: ^1.12.2
  json_serializable: ^4.1.0
  mocktail: ^0.1.1
