name: firesearch_sdk
description: An sdk for Firesearch
version: 0.1.5
repository: https://github.com/uris77/firesearch_sdk
homepage: https://github.com/uris77/firesearch_sdk

environment:
  sdk: ^3.4.0

dependencies:
  http: ^1.2.1
  meta: ^1.3.0
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.1

dev_dependencies:
  test: ^1.25.7
  very_good_analysis: ^5.1.0
  freezed: ^2.5.3
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  mocktail: ^1.0.4

#dependency_overrides:
#  logging: 1.1.1