name: firesearch_sdk
description: An sdk for Firesearch
version: 0.1.0

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  http: ^0.13.1
  meta: ^1.3.0

dev_dependencies:
  test: ^1.16.8
  very_good_analysis: ^2.0.0

